spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        greetings-in:
          group: customer-save
          destination: greetings
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json

server:
     port: 0